

server:
  port: 1111  # 서버 포트 설정

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/busTime
    username: root
    password: biology00
  thymeleaf:
    cache: false

  # ✅ WebSocket 설정 추가
  websocket:
    enabled: true


  # ✅ Spring Data JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
  application:
    name: BusTime_backend

# ✅ 스케줄러 활성화
management:
  endpoint:
    scheduling:
      enabled: true

public-api:
  service-key: tNbsVnMlaZ7jFtVUDgBJTlDNg%2FVFa7R7XUYyegbItZY61%2FL%2FSgsl%2BFUP39TKdewZ5gwiPvYv3oaL6Zx8fv5iBg%3D%3D

bus:
  api:
    bus-location:
      api-url: https://apis.data.go.kr/1613000/BusLcInfoInqireService/getRouteAcctoBusLcList
    info:
      api-url: https://apis.data.go.kr/1613000/BusRouteInfoInqireService/getRouteNoList
    stop-location:
      api-url: https://apis.data.go.kr/1613000/ArvlInfoInqireService/getSttnAcctoArvlPrearngeInfoList
    stop-time:
      api-uri: https://apis.data.go.kr/1613000/ArvlInfoInqireService/getSttnAcctoArvlPrearngeInfoList

    city-code: 38320
    page-no: 1
    num-of-rows: 200
    type: json
  routes:
    to-fetch: 113,250